-- 여행 등록 시 사용자가 고른 "걱정되는 상황"을 담는다.
--
-- 항목이 11개로 고정돼 있어 마스터 테이블 대신 Java enum(Concern)으로 두고, 선택 결과만
-- 배열 컬럼 하나에 저장한다. 라벨과 노출 순서도 enum이 들고 있어 시드 데이터가 필요 없다.
--
-- CSV 문자열이 아니라 배열을 쓰는 이유: "어떤 걱정이 많이 선택되는가"를 볼 때
-- concerns @> ARRAY['FLIGHT_DELAY'] 로 조회할 수 있다. CSV면 LIKE 로 긁어야 하고
-- 부분 일치 오탐이 난다.
--
-- ⚠️ 다른 enum 컬럼과 달리 CHECK 제약을 걸지 않는다. 배열에 CHECK 를 걸면 걱정 항목을
-- 추가할 때마다 마이그레이션이 필요해져 enum 으로 둔 이점이 사라진다. 허용값 검증은
-- 요청을 Concern 으로 역직렬화하는 단계에서 이뤄진다(잘못된 코드는 400).
ALTER TABLE trips ADD COLUMN concerns varchar(50)[] NOT NULL DEFAULT '{}';
